// DO NOT USE - USE SERVER.JS 
// THIS IS JUST FOR SERENA TO REFERENCE

// Import required modules
const express = require('express');
const multer = require('multer');
const mongoose = require('mongoose');
const path = require('path');
const bodyParser = require('body-parser');
require('dotenv').config(); // Load environment variables
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { Upload } = require('@aws-sdk/lib-storage'); // Import Upload class from AWS SDK v3

// Initialize the app
const app = express();
const PORT = 3000;

// Middleware
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static('public'));

// MongoDB connection
const MONGO_URI = 'mongodb://localhost:27017/uploadDB';
mongoose.connect(MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Define FileUpload schema
const fileUploadSchema = new mongoose.Schema({
  filename: String,
  url: String, // S3 URL
  name: String,
  email: String,
  datasetName: String,
  celltypeLabel: Boolean,
  celltypeLabelText: String,
  autoGeneratedColors: Boolean,
  UNSColumn: String,
  colorsJSON: String,
  rawGeneCounts: Boolean,
  rawGeneCountsText: String,
  uploadDate: { type: Date, default: Date.now },
  uploadId: String,
  parts: [{ ETag: String, PartNumber: Number }],
});

const FileUpload = mongoose.model('FileUpload', fileUploadSchema); // Renamed to FileUpload

// ✅ Corrected S3Client initialization
const s3Client = new S3Client({
  region: process.env.AWS_REGION,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  },
});

// Set up Multer for handling file uploads
const storage = multer.memoryStorage(); // Store file in memory for direct S3 upload
const upload = multer({ storage });

// Routes
// GET / - Serve the HTML page
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// POST /upload - Handle file uploads to S3 and save to database
app.post('/upload', upload.fields([
  { name: 'h5adfile', maxCount: 1 },
  { name: 'JSON', maxCount: 1 } // Allow JSON file upload
]), async (req, res) => {
  try {
    if (!req.files || !req.files['h5adfile']) {
      console.log('Files received:', req.files);
      console.log('Form data:', req.body);

      return res.status(400).send('No file uploaded.');
    }

    const { name, email, dataset_name, celltype_label, celltype_label_text, auto_generated_colors, UNS_column, raw_gene_counts, raw_gene_counts_text } = req.body;

    const filename = `${Date.now()}-${req.files['h5adfile'][0].originalname}`;
    const bucketName = process.env.S3_BUCKET_NAME;

    // ✅ Use Upload with a valid S3Client instance
    const parallelUploads3 = new Upload({
      client: s3Client,
      params: {
        Bucket: bucketName,
        Key: filename,
        Body: req.files['h5adfile'][0].buffer,
        ContentType: req.files['h5adfile'][0].mimetype,
      },
    });

    const uploadResult = await parallelUploads3.done(); // Perform the upload

    let jsonFileUrl = null;
    if (req.files['JSON']) {
      const jsonFilename = `${Date.now()}-${req.files['JSON'][0].originalname}`;

      const jsonUpload = new Upload({
        client: s3Client,
        params: {
          Bucket: bucketName,
          Key: jsonFilename,
          Body: req.files['JSON'][0].buffer,
          ContentType: req.files['JSON'][0].mimetype,
        },
      });

      await jsonUpload.done();
      jsonFileUrl = `https://${bucketName}.s3.${process.env.AWS_REGION}.amazonaws.com/${jsonFilename}`;
    }

    // Save the file metadata to MongoDB
    const newFileUpload = new FileUpload({
      filename,
      url: `https://${bucketName}.s3.${process.env.AWS_REGION}.amazonaws.com/${filename}`,
      name,
      email,
      datasetName: dataset_name,
      celltypeLabel: celltype_label === 'on',
      celltypeLabelText: celltype_label_text || null,
      autoGeneratedColors: auto_generated_colors === 'on',
      UNSColumn: UNS_column || null,
      colorsJSON: jsonFileUrl,
      rawGeneCounts: raw_gene_counts === 'on',
      rawGeneCountsText: raw_gene_counts_text || null,
    });

    await newFileUpload.save();
    res.status(200).send(`File uploaded to S3 and saved to database successfully! URL: ${newFileUpload.url}`);
  } catch (err) {
    console.error('Error uploading file:', err);
    res.status(500).send('Error uploading file.');
  }
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
